nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: [ 'GET','OPTIONS','POST','PUT','PATCH','DELETE' ]
        # TODO: This messes up stuff, figure out wassup
        allow_headers: [ '*' ]
        expose_headers: [ 'Link' ]
        max_age: 3600
    paths:
        '^/api/': ~
